### ISSUE TITLE
KeyError: 'bar'

### ISSUE THREAD

**Issue by spoeken** [andyjsmith/SmugMug-Downloader#13]
Hi, I'm getting this error, using python3.7

Downloading album list...done.
Creating output directories...done.
Traceback (most recent call last):
  File "smdl.py", line 78, in <module>
    desc=f"{fg('yellow')}{attr('bold')}{format_label('All Albums')}{attr('reset')}"):
  File "/Users/mathias/.pyenv/versions/3.7.1/envs/gpt/lib/python3.7/site-packages/tqdm/_tqdm.py", line 945, in __init__
    self.display()
  File "/Users/mathias/.pyenv/versions/3.7.1/envs/gpt/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1315, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/Users/mathias/.pyenv/versions/3.7.1/envs/gpt/lib/python3.7/site-packages/tqdm/_tqdm.py", line 984, in __repr__
    return self.format_meter(**self.format_dict)
  File "/Users/mathias/.pyenv/versions/3.7.1/envs/gpt/lib/python3.7/site-packages/tqdm/_tqdm.py", line 419, in format_meter
    return bar_format.format(**format_dict)
KeyError: 'bar'

**Comment by andyjsmith** [comment]
That seems like an issue with tqdm. Try updating your version of tqdm with pip, that seems to have solved similar issues in other programs (https://github.com/iterative/dvc/issues/2486).
