### ISSUE TITLE
KeyError: 'bar'

### ISSUE THREAD

**Issue by pirx242** [andyjsmith/SmugMug-Downloader#25]
Hi! Trying to download and get this almost right away:)

```
akol@TT112:~/smugmug/smdl/SmugMug-Downloader$ python3 ./smdl.py -s ... -u user...
Downloading album list...done.
Creating output directories...done.
Traceback (most recent call last):
  File "./smdl.py", line 94, in <module>
    for album in tqdm(albums["Response"]["AlbumList"], position=0, leave=True, bar_format=bar_format,
  File "/usr/lib/python3/dist-packages/tqdm/_tqdm.py", line 923, in __init__
    self.display()
  File "/usr/lib/python3/dist-packages/tqdm/_tqdm.py", line 1293, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/usr/lib/python3/dist-packages/tqdm/_tqdm.py", line 962, in __repr__
    return self.format_meter(**self.format_dict)
  File "/usr/lib/python3/dist-packages/tqdm/_tqdm.py", line 409, in format_meter
    return bar_format.format(**format_dict)
KeyError: 'bar'
```

**Comment by andyjsmith** [comment]
See #13, you just need to update tqdm
